# Generated by Django 4.1.7 on 2023-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('user_creation_date', models.DateTimeField()),
            ],
        ),
    ]
