# Generated by Django 4.1.7 on 2023-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
