# Generated by Django 4.1.7 on 2023-03-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=2000)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
